# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PY 101-012 - Spring 2016 (UA)
email: jmbeach1@crimson.ua.edu
description: > # this means to ignore newlines until "baseurl:"
  Website for notes and other study materials from University of Alabama's Pyschology 101 section 012 Spring 2016
# baseurl: ""
#comment above on publish and uncomment below
baseurl: "/PY101-012" # the subpath of your site, e.g. /blog
url: "http://jmbeach.github.io/PY101-012" # the base hostname & protocol for your site
# twitter_username: hey_beach
github_username:  jmbeach

# Build settings
markdown: kramdown
